# Generated by Django 4.2.7 on 2025-10-01 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('loan_approval', 'Loan Approval'), ('loan_rejection', 'Loan Rejection'), ('payment_due', 'Payment Due'), ('payment_received', 'Payment Received'), ('guarantor_request', 'Guarantor Request'), ('share_purchase', 'Share Purchase'), ('dividend_payout', 'Dividend Payout'), ('system_announcement', 'System Announcement'), ('account_activity', 'Account Activity')], max_length=20)),
                ('channels', models.JSONField(default=list)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
